{% set name = "pingouin" %}
{% set version = "0.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 68b734a8ba368bdf3d43ede99f9267ec4522d34786ad1ec840938f0df36add5f

build:
  noarch: python
  number: 0
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.16.5
    - scipy >=1.3.0
    - pandas >=0.24
    - matplotlib-base >=3.0.2
    - seaborn >=0.9.0
    - statsmodels >=0.10.0
    - scikit-learn
    - pandas-flavor >=0.1.2
    - mpmath
    - outdated
    - tabulate

test:
  imports:
    - pingouin
    - pingouin.datasets

about:
  home: https://pingouin-stats.org/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Pingouin is an open-source statistical package written in Python 3 and based mostly on Pandas and NumPy

  description: |
    Pingouin is designed for users who want simple yet exhaustive statistical functions.
    For example, the scipy.stats.ttest_ind() function returns only the T-value and the p-value.
    By contrast, the pingouin.ttest() function returns the T-value, p-value, degrees of freedom,
    effect size (Cohen’s d), statistical power and Bayes Factor (BF10) of the test.

  doc_url: https://pingouin-stats.org/
  dev_url: https://github.com/raphaelvallat/pingouin

extra:
  recipe-maintainers:
    - hoechenberger
    - raphaelvallat
