{% set name = "pingouin" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7530eb7665d478b7d7da8cae3cdfca8ccb829b29eba1d1bf885fcbff3b23c64b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.19
    - scipy >=1.7
    - pandas >=1.0
    - matplotlib-base >=3.0.2
    - seaborn >=0.9.0
    - statsmodels >=0.12.0
    - scikit-learn
    - pandas-flavor >=0.2.0
    - mpmath
    - outdated
    - tabulate

test:
  imports:
    - pingouin
    - pingouin.datasets

about:
  home: https://pingouin-stats.org/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Pingouin is an open-source statistical package written in Python 3 and based mostly on Pandas and NumPy

  description: |
    Pingouin is designed for users who want simple yet exhaustive statistical functions.
    For example, the scipy.stats.ttest_ind() function returns only the T-value and the p-value.
    By contrast, the pingouin.ttest() function returns the T-value, p-value, degrees of freedom,
    effect size (Cohen’s d), statistical power and Bayes Factor (BF10) of the test.

  doc_url: https://pingouin-stats.org/
  dev_url: https://github.com/raphaelvallat/pingouin

extra:
  recipe-maintainers:
    - hoechenberger
    - raphaelvallat
