travis:
  secure:
    BINSTAR_TOKEN: J9flvjXVlY4dgcS31h50M607KdWNLbHA49rmTpHF0R3l0McBgcDGVfSVjTt5fgkqUPUHp49KAO2CZjbMEUSeQ05b8V6N9ZBs1pr4R2mFSRK80/vZ0rnxZ3MlgX5arhBtaerkQnpmtSUysDTvjU+zI24DEk+JzE4buKx6q8lguqOxq3JbHVW3+Ohi3W0RS0gXyy7b/TfSpg+47h70Eq6kQ65+1LRGomM6ifWYig0eFHXKR4YF76DmDw6Xjx7vwOwJ/rDaZiQwTXNTl4guBvHSfYm+fnpxEe7exy3QNJBZbAgQYU7DVnvPjJgzDUpaEDawkxCMmcigdYYvfToijTp60LmWFaGfMkmcJLb4ohjSHAsl1xHWKdEf1l32ev8Llw5EGvUUvRTGD7BgItL9UzpAoW8OqtDTiIKWmyqV8Bj9lxQOm58TdQ5CEx2/L54EZaT+dyNeh5E9REPNLM20Fz+JefS7XxitS8Lt2tNM2OA+tkQXnyKaD4oQCAbdFJhAMYxZJyLo2lBi3rH2VbLiW0roR6RzHtDZ3HXhM1Xu/JaUsBaCfb9P8+eomZefCwbocZ218i0LedCqNYdEMOd/g6cZK1S5DkOtKHeyPn+bf1UvEn9IGAgioPpmueJ0RG23pBlsAzgc77LTOP1Bls3OIf7SA4urULlXFpmQkqHl2K0mwO4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
